server:
  log_level: info
  http_listen_port: 12345

metrics:
  global:
    external_labels:
      origin_prometheus: yearnapi
    scrape_interval: 1m
    remote_write:
    - url: ${REMOTE_WRITE}
      basic_auth:
        username: ${REMOTE_WRITE_USERNAME}
        password: ${REMOTE_WRITE_PASSWORD}

  configs:
    - name: yearnapi
      scrape_configs:
        - job_name: yearnapi
          static_configs:
            - targets: ['api:${PORT}']

